### ISSUE TITLE
Error loading script

### ISSUE THREAD

**Issue by DeeVeeAkkun** [aria1th/Hypernetwork-MonkeyPatch-Extension#15]
Installed the Extension using the webUI and this is what I get. Anyone got any possible solutions? 

Error loading script: hypernetwork-extensions.py
Traceback (most recent call last):
  File "D:\diffusion\stable-diffusion-webui\modules\scripts.py", line 171, in load_scripts
    exec(compiled, module.__dict__)
  File "D:\diffusion\stable-diffusion-webui\extensions\Hypernetwork-MonkeyPatch-Extension\scripts\hypernetwork-extensions.py", line 19, in <module>
    def create_training_tab(params: script_callbacks.UiTrainTabParams = None):
AttributeError: module 'modules.script_callbacks' has no attribute 'UiTrainTabParams'

**Comment by aria1th** [comment]
I'm not sure, I cannot reproduce the issue in main commit hash 9092e1ca7756642692197316d3dec47c23322381.
Does it happen in recent webui too?
