### ISSUE TITLE
WebUI error

### ISSUE THREAD

**Issue by RevyaM** [aria1th/Hypernetwork-MonkeyPatch-Extension#27]
After the two webui updates I've started getting this error when training an embedding: 
raceback (most recent call last):
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 284, in run_predict
    output = await app.blocks.process_api(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 982, in process_api
    result = await self.call_function(fn_index, inputs, iterator)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 824, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\stable-diffusion-webui\modules\ui_progress.py", line 89, in <lambda>
    fn=lambda: check_progress_call(id_part),
  File "D:\stable-diffusion-webui\modules\ui_progress.py", line 56, in check_progress_call
    shared.state.set_current_image()
  File "D:\stable-diffusion-webui\modules\shared.py", line 229, in set_current_image
    self.do_set_current_image()
  File "D:\stable-diffusion-webui\modules\shared.py", line 237, in do_set_current_image
    self.current_image = modules.sd_samplers.samples_to_image_grid(self.current_latent)
  File "D:\stable-diffusion-webui\modules\sd_samplers.py", line 135, in samples_to_image_grid
    return images.image_grid([single_sample_to_image(sample, approximation) for sample in samples])
  File "D:\stable-diffusion-webui\modules\sd_samplers.py", line 135, in <listcomp>
    return images.image_grid([single_sample_to_image(sample, approximation) for sample in samples])
  File "D:\stable-diffusion-webui\modules\sd_samplers.py", line 122, in single_sample_to_image
    x_sample = processing.decode_first_stage(shared.sd_model, sample.unsqueeze(0))[0]
  File "D:\stable-diffusion-webui\modules\processing.py", line 408, in decode_first_stage
    x = model.decode_first_stage(x)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 826, in decode_first_stage
    return self.first_stage_model.decode(z)
  File "D:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\autoencoder.py", line 89, in decode
    z = self.post_quant_conv(z)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\conv.py", line 453, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (torch.cuda.HalfTensor) and weight type (torch.HalfTensor) should be the same

Both extension and webui are fully updated and the training works as usual, but the web page itself just bugs out and stops showing any progress past 42 steps (just freezes on that one). Starting a new training or continuing to train an existing embedding resets the UI, shows the proper steps but does the same thing again on 49s step done.

**Comment by aria1th** [comment]
Does that happen in original webui (without extension) too? Unfortunately I wasn't able to get that error, usually it happens when optimizer or model is unloaded while generating preview image.

**Comment by RevyaM** [comment]
Tried using vanilla embedding training, the UI there is updated and works fine.

**Comment by aria1th** [comment]
![image](https://user-images.githubusercontent.com/35677394/212523416-c4c9032d-5a11-4ac7-abb2-ad775859a0ee.png)
I still cannot find anything, well....
What webpage is bugging? txt2img tab? or training tab? 
also by step, do you mean 'training step'? or 'sampling step'?

**Comment by RevyaM** [comment]
The webpage that is bugging out is a extension's training tab. 
By step I meant a training step. From what I saw, at the start of a new embedding training it would "freeze" at 42 steps. After continuing it would freeze at 45 or 49. When continuing it would also try to render a preview image and it seems that sometimes it stops at early sampling steps. 
While that happens, the training itself would go just fine and preview images in folder would also be "completed", ever if a preview on a webpage would show otherwise. 

I will try completely reinstalling extension in a few hours to see if it'll fix the issue or not.

**Comment by aria1th** [comment]
Preview images will never correctly shown in training UI, since its digest version. You can check correct image in folder, or in txt2img tab. But freezing sounds weird, well at least that RuntimeError that interrupts training should not happen. Still I cannot find the error that would raise that error....

**Comment by RevyaM** [comment]
Made a clear installation, gone to step 49 and the same error. 
No saved optimizer exists in checkpoint
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:06<00:00,  2.96it/s]
Traceback (most recent call last):█████████████████████████████████████████████████████| 20/20 [00:06<00:00,  4.00it/s]
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 284, in run_predict
    output = await app.blocks.process_api(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 982, in process_api
    result = await self.call_function(fn_index, inputs, iterator)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 824, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\stable-diffusion-webui\modules\ui_progress.py", line 89, in <lambda>
    fn=lambda: check_progress_call(id_part),
  File "D:\stable-diffusion-webui\modules\ui_progress.py", line 56, in check_progress_call
    shared.state.set_current_image()
  File "D:\stable-diffusion-webui\modules\shared.py", line 229, in set_current_image
    self.do_set_current_image()
  File "D:\stable-diffusion-webui\modules\shared.py", line 237, in do_set_current_image
    self.current_image = modules.sd_samplers.samples_to_image_grid(self.current_latent)
  File "D:\stable-diffusion-webui\modules\sd_samplers.py", line 135, in samples_to_image_grid
    return images.image_grid([single_sample_to_image(sample, approximation) for sample in samples])
  File "D:\stable-diffusion-webui\modules\sd_samplers.py", line 135, in <listcomp>
    return images.image_grid([single_sample_to_image(sample, approximation) for sample in samples])
  File "D:\stable-diffusion-webui\modules\sd_samplers.py", line 122, in single_sample_to_image
    x_sample = processing.decode_first_stage(shared.sd_model, sample.unsqueeze(0))[0]
  File "D:\stable-diffusion-webui\modules\processing.py", line 408, in decode_first_stage
    x = model.decode_first_stage(x)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 826, in decode_first_stage
    return self.first_stage_model.decode(z)
  File "D:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\autoencoder.py", line 90, in decode
    dec = self.decoder(z)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\model.py", line 637, in forward
    h = self.up[i_level].block[i_block](h, temb)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\model.py", line 131, in forward
    h = self.norm1(h)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\normalization.py", line 272, in forward
    return F.group_norm(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\functional.py", line 2516, in group_norm
    return torch.group_norm(input, num_groups, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument weight in method wrapper__native_group_norm)

![image](https://user-images.githubusercontent.com/40909979/212550284-a252d7f9-d2e6-4edb-b466-e7180ef8e2cf.png)

This is how it looks.

**Comment by aria1th** [comment]
Can you check these options state?
Unload Optimizer when generating preview(hypernetwork)
Move VAE and CLIP to RAM when training if possible. Saves VRAM.
Turn on pin_memory for DataLoader. Makes training slightly faster but can increase memory usage.

**Comment by aria1th** [comment]
Related issue is here, but still not sure, I'm totally reworking some code part.
is https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/6764 related to you?

**Comment by RevyaM** [comment]
I did move clip to ram and disabled vae while training. 
Basically I am using the very same settings I've been using a few weeks ago and they were working just fine, it seems to have started bugging after recent two updates. No idea why, given that the settings and datasets were pretty much the same. 
Once again, the training itself works as per usual and even the webpage itself is functional, it just that it visually freezes on a step 42 or 49 prior generating a preview. 

I will see if pin mem does change something in a few hours, although I am not sure if 3060ti can handle it.

**Comment by aria1th** [comment]
I guess its something related to asyncio stuff, I'm testing some fixes. It might take an hour to test the code before release.

**Comment by aria1th** [comment]
Can you try with most recent release?

**Comment by RevyaM** [comment]
Seems to be fixed, although I couldn't train the old embedding because "No inf checks were recorded for this optimizer". New one works just as it should.

**Comment by aria1th** [comment]
You cannot train from existing checkpoint? does removing (or changing name) of the .optim file solves the issue?

**Comment by RevyaM** [comment]
I didn't check prior completely removing it, my bad. It might also been a vanilla embedding, given that it has a pretty similar name to a monkeypatch one. Creating a new one allows training and to continue training. 
However, I noticed a similar error to a first one in hypernetwork training: 
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\stable-diffusion-webui\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "D:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 43, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "D:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "D:\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 163, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\stable-diffusion-webui\modules\progress.py", line 82, in progressapi
    shared.state.set_current_image()
  File "D:\stable-diffusion-webui\modules\shared.py", line 233, in set_current_image
    self.do_set_current_image()
  File "D:\stable-diffusion-webui\modules\shared.py", line 241, in do_set_current_image
    self.assign_current_image(modules.sd_samplers.samples_to_image_grid(self.current_latent))
  File "D:\stable-diffusion-webui\modules\sd_samplers.py", line 135, in samples_to_image_grid
    return images.image_grid([single_sample_to_image(sample, approximation) for sample in samples])
  File "D:\stable-diffusion-webui\modules\sd_samplers.py", line 135, in <listcomp>
    return images.image_grid([single_sample_to_image(sample, approximation) for sample in samples])
  File "D:\stable-diffusion-webui\modules\sd_samplers.py", line 122, in single_sample_to_image
    x_sample = processing.decode_first_stage(shared.sd_model, sample.unsqueeze(0))[0]
  File "D:\stable-diffusion-webui\modules\processing.py", line 408, in decode_first_stage
    x = model.decode_first_stage(x)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 826, in decode_first_stage
    return self.first_stage_model.decode(z)
  File "D:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\autoencoder.py", line 89, in decode
    z = self.post_quant_conv(z)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\conv.py", line 453, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (torch.cuda.HalfTensor) and weight type (torch.HalfTensor) should be the same
Applying xformers cross attention optimization.

It doesn't freeze during the training itself, but does so when it's finished/interrupted. 
Just as that time, it doesn't affect training itself, just gives this error in the console and freezes the webpage until you resume training/start a new one.

**Comment by RevyaM** [comment]
> Related issue is here, but still not sure, I'm totally reworking some code part. is [AUTOMATIC1111/stable-diffusion-webui#6764](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/6764) related to you?

Concerning that one - no, never had a similar problem with webui.

**Comment by aria1th** [comment]
For training embedding I think you used template that does not contain [name]

**Comment by RevyaM** [comment]
> For training embedding I think you used template that does not contain [name]

I cannot be certain about this, but I think the only thing I've done is that I deleted the embedding and made a new one with the same name. 
My templates are just a bunch of " [filewords], [name] " lines

**Comment by RevyaM** [comment]
The hypernetwork error seems to be fixed with the last patch
