### ISSUE TITLE
Key error when attempting to train

### ISSUE THREAD

**Issue by tranzmatt** [aria1th/Hypernetwork-MonkeyPatch-Extension#28]
I'm trying to train an embedding on a data set I successfully trained with the standard Training tab, but get the following error:

```
To create a public link, set `share=True` in `launch()`.
Error completing request
Arguments: ('task(j8c78et9xuqk85m)', '0.005', 1, 1, '/home/sd/Datasets/Button/Processed', 'textual_inversion', 512, 512, 3000, False, 0, 'once', 500, 500, '/home/sd/stable-diffusion-webui/textual_inversion_templates/custom_filewords.txt', True, False, '', '', 20, 0, 7, -1.0, 512, 512, False, '64', '1', '5', '6e-7', '1', False, False, True, False, '0.01', '0.9', '0.99', '1e-8', False, '', '1e-1', '2') {}
Traceback (most recent call last):
  File "/home/sd/stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/home/sd/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/home/sd/stable-diffusion-webui/extensions/Hypernetwork-MonkeyPatch-Extension/patches/external_pr/textual_inversion.py", line 193, in train_embedding
    hijack = sd_hijack.model_hijack
KeyError: 'task(j8c78et9xuqk85m)'
```

I didn't make any changes beyond setting the dataset folder and lowering the Max Steps to 3000, so I'm not sure what the issue is.  I have the latest version of webui and commit hash of MonkeyPatch, 7631f51b428cb3eedc2e38a7aa4aa96ca766a001

**Comment by aria1th** [comment]
Can you restart UI? 
`'task(j8c78et9xuqk85m)', '0.005', 1, 1`
this is missing name space, something is weird...
