### ISSUE TITLE
cannot import name 'fix_checkpoint' from 'modules.sd_hijack'

### ISSUE THREAD

**Issue by etherealxx** [aria1th/Hypernetwork-MonkeyPatch-Extension#33]
I used your extension several times before, great extension. however, i encountered this problem today (after about 4 days not doing any training).
```
Error loading script: hypernetwork-extensions.py
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 205, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/stable-diffusion-webui/extensions/Hypernetwork-MonkeyPatch-Extension/scripts/hypernetwork-extensions.py", line 11, in <module>
    import patches.clip_hijack as clip_hijack
  File "/content/stable-diffusion-webui/extensions/Hypernetwork-MonkeyPatch-Extension/patches/clip_hijack.py", line 2, in <module>
    from modules.sd_hijack import StableDiffusionModelHijack, EmbeddingsWithFixes, apply_optimizations, fix_checkpoint
ImportError: cannot import name 'fix_checkpoint' from 'modules.sd_hijack' (/content/stable-diffusion-webui/modules/sd_hijack.py)
```
and the training_gamma tab wont show
![image](https://user-images.githubusercontent.com/64251396/213342427-d31dbc82-bf68-466a-b2bf-645091a4fbd5.png)

something wrong with your updated extension or something wrong with the current commit of auto1111's webui?

**Comment by aria1th** [comment]
about 9 hours ago, the function is removed - so I'll fix it. I'm just testing new release- it will be done within 30 minutes!

**Comment by aria1th** [comment]
![image](https://user-images.githubusercontent.com/35677394/213362959-121e6b4d-713b-4fd1-b8cc-1c63f8322484.png)
@etherealxx 
It should be fixed with most recent patch, please check it!
