### ISSUE TITLE
automatic1111 breaking changes it seems

### ISSUE THREAD

**Issue by khushil** [aria1th/Hypernetwork-MonkeyPatch-Extension#40]
Got the following after a git pull this AM:

Error loading script: hypernetwork-extensions.py
Traceback (most recent call last):
  File "G:\AI\stable-diffusion-webui\modules\scripts.py", line 218, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "G:\AI\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "G:\AI\stable-diffusion-webui\extensions\Hypernetwork-MonkeyPatch-Extension\scripts\hypernetwork-extensions.py", line 13, in <module>
    import patches.ui as ui
  File "G:\AI\stable-diffusion-webui\extensions\Hypernetwork-MonkeyPatch-Extension\patches\ui.py", line 4, in <module>
    from .hypernetwork import Hypernetwork, load_hypernetwork
  File "G:\AI\stable-diffusion-webui\extensions\Hypernetwork-MonkeyPatch-Extension\patches\hypernetwork.py", line 10, in <module>
    import scripts.xy_grid
ModuleNotFoundError: No module named 'scripts.xy_grid'

**Comment by aria1th** [comment]
@khushil 
I fixed in https://github.com/aria1th/Hypernetwork-MonkeyPatch-Extension/commit/0428c6e47aeddd9c8e3f12ae2666e4e7078d6c66 but there could be more errors, can you test it?

**Comment by randsley** [comment]
I see automatic1111 replaced scripts.xy_grid.py with scripts_xyz.py

**Comment by khushil** [comment]
@aria1th  many thanks mate, confirmed fixed. Just in case anyone else is struggling, I was advised to remove venv (other issues as well) and let it reinstall all the things.
