### ISSUE TITLE
ModuleNotFoundError: No module named 'scripts.xy_grid'

### ISSUE THREAD

**Issue by Zyin055** [aria1th/Hypernetwork-MonkeyPatch-Extension#42]
I updated the Web UI today to A1111 commit 2c1bb46c7ad5b4536f6587d327a03f0ff7811c5d and now get this error when booting up:

```
Error loading script: hypernetwork-extensions.py
Traceback (most recent call last):
  File "C:\Stuff\AI\Stable Diffusion\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Stuff\AI\Stable Diffusion\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Stuff\AI\Stable Diffusion\extensions\Hypernetwork-MonkeyPatch-Extension\scripts\hypernetwork-extensions.py", line 13, in <module>
    import patches.ui as ui
  File "C:\Stuff\AI\Stable Diffusion\extensions\Hypernetwork-MonkeyPatch-Extension\patches\ui.py", line 5, in <module>
    from .hypernetwork import Hypernetwork, train_hypernetwork, load_hypernetwork
  File "C:\Stuff\AI\Stable Diffusion\extensions\Hypernetwork-MonkeyPatch-Extension\patches\hypernetwork.py", line 15, in <module>
    import scripts.xy_grid
ModuleNotFoundError: No module named 'scripts.xy_grid'
```

I'm pretty sure this is because the original xy_grid.py file we all know and love was renamed to xyz_grid.py in an A1111 update sometime between 1/6/22 and 1/31/22.

Because of this error the training tab is not created and the extension is not usable.

**Comment by Zyin055** [comment]
Updating fixed it.

For some reason updating the extension through the Web UI failed to grab the latest update, had to `git pull` manually.
