### ISSUE TITLE
Error loading script: hypernetwork-extensions.py

### ISSUE THREAD

**Issue by kintama123** [aria1th/Hypernetwork-MonkeyPatch-Extension#44]
I installed this for the frist time and got this message

Error loading script: hypernetwork-extensions.py
Traceback (most recent call last):
  File "C:\ai\stable-diffusion-webui\modules\scripts.py", line 205, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\ai\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\ai\stable-diffusion-webui\extensions\Hypernetwork-MonkeyPatch-Extension\scripts\hypernetwork-extensions.py", line 13, in <module>
    import patches.ui as ui
  File "C:\ai\stable-diffusion-webui\extensions\Hypernetwork-MonkeyPatch-Extension\patches\ui.py", line 4, in <module>
    from .hypernetwork import Hypernetwork, load_hypernetwork
  File "C:\ai\stable-diffusion-webui\extensions\Hypernetwork-MonkeyPatch-Extension\patches\hypernetwork.py", line 10, in <module>
    from modules.sd_samplers_kdiffusion import KDiffusionSampler
ModuleNotFoundError: No module named 'modules.sd_samplers_kdiffusion'

any fix?

**Comment by aria1th** [comment]
This is minor bug from unused imports. Now I pushed commit that fixes the problem.
