### ISSUE TITLE
UnboundLocalError: local variable 'hypernetwork' referenced before assignment

### ISSUE THREAD

**Issue by oO0** [aria1th/Hypernetwork-MonkeyPatch-Extension#53]
when press train hypernetwork (gamma).
A1111 v1.4.0

 `Traceback (most recent call last):
      File "G:\Automatic111\extensions\Hypernetwork-MonkeyPatch-Extension\patches\external_pr\hypernetwork.py", line 208, in train_hypernetwork
        warmup = int(warmup)
    ValueError: invalid literal for int() with base 10: '21.5'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "G:\Automatic111\extensions\Hypernetwork-MonkeyPatch-Extension\patches\external_pr\ui.py", line 28, in train_hypernetwork_ui
        hypernetwork, filename = train_hypernetwork_external(*args)
      File "G:\Automatic111\extensions\Hypernetwork-MonkeyPatch-Extension\patches\external_pr\hypernetwork.py", line 221, in train_hypernetwork
        raise RuntimeError("Cannot use advanced LR scheduler settings!")
    RuntimeError: Cannot use advanced LR scheduler settings!

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "G:\Automatic111\modules\call_queue.py", line 55, in f
        res = list(func(*args, **kwargs))
      File "G:\Automatic111\modules\call_queue.py", line 35, in f
        res = func(*args, **kwargs)
      File "G:\Automatic111\extensions\Hypernetwork-MonkeyPatch-Extension\patches\external_pr\ui.py", line 42, in train_hypernetwork_ui
        del hypernetwork
    UnboundLocalError: local variable 'hypernetwork' referenced before assignment`

**Comment by aria1th** [comment]
@oO0 Seems like you are using 21.5 for warmup step, but it expects int - I'll make it round the value.
But if it was unexpected (or using some different setup), can you show the setting you used? I cannot reproduce the exact error except warmup value must be integer, not float...
