### ISSUE TITLE
Extension throws error since recent stable-diffusion-webui updates, doesn't work anymore.

### ISSUE THREAD

**Issue by FullTablet** [aria1th/Hypernetwork-MonkeyPatch-Extension#54]
While loading stable-diffusion-webui, this error shows up when the Hypernetwork-MonkeyPatch-Extension is enabled. Then, the extension doesn't run.

*** Error loading script: hypernetwork-extensions.py
    Traceback (most recent call last):
      File "L:\stable-diffusion-webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "L:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "L:\stable-diffusion-webui\extensions\Hypernetwork-MonkeyPatch-Extension\scripts\hypernetwork-extensions.py", line 15, in <module>
        import patches.external_pr.ui as external_patch_ui
      File "L:\stable-diffusion-webui\extensions\Hypernetwork-MonkeyPatch-Extension\patches\external_pr\ui.py", line 13, in <module>
        from .hypernetwork import train_hypernetwork as train_hypernetwork_external, train_hypernetwork_tuning
      File "L:\stable-diffusion-webui\extensions\Hypernetwork-MonkeyPatch-Extension\patches\external_pr\hypernetwork.py", line 15, in <module>
        from modules.hypernetworks.hypernetwork import optimizer_dict, stack_conds, save_hypernetwork, report_statistics
    ImportError: cannot import name 'report_statistics' from 'modules.hypernetworks.hypernetwork' (L:\stable-diffusion-webui\modules\hypernetworks\hypernetwork.py)

**Comment by aria1th** [comment]
@FullTablet thank you for reporting the issue! I'll try to fix the issue within 12 hours, but due to massive change, I might release the patch without previous version compatibility.

**Comment by aria1th** [comment]
@FullTablet I just pushed the fix, it was simple - but I didn't test if training / other features are working... if you see its broken, please ping me!
(well I'll trying to just implement lora training as extension instead now...)
