### ISSUE TITLE
Error after saving image at the end of cycle

### ISSUE THREAD

**Issue by Lukxie** [aria1th/Hypernetwork-MonkeyPatch-Extension#6]
![image](https://user-images.githubusercontent.com/115797570/204138954-40b16f5a-8e09-460f-8ba6-1bb9415b87d5.png)

This error ocurrs after generating and saving the image

File "/notebooks/stable-diffusion-webui/extensions/Hypernetwork-MonkeyPatch-Extension-main/patches/external_pr/hypernetwork.py", line 213, in train_hypernetwork
    scaler.step(optimizer)
  File "/usr/local/lib/python3.9/dist-packages/torch/cuda/amp/grad_scaler.py", line 338, in step
    retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/cuda/amp/grad_scaler.py", line 285, in _maybe_opt_step
    retval = optimizer.step(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/optim/lr_scheduler.py", line 65, in wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/optim/optimizer.py", line 109, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/optim/adamw.py", line 161, in step
    adamw(params_with_grad,
  File "/usr/local/lib/python3.9/dist-packages/torch/optim/adamw.py", line 218, in adamw
    func(params,
  File "/usr/local/lib/python3.9/dist-packages/torch/optim/adamw.py", line 259, in _single_tensor_adamw
    assert not step_t.is_cuda, "If capturable=False, state_steps should not be CUDA tensors."
AssertionError: If capturable=False, state_steps should not be CUDA tensors.

**Comment by aria1th** [comment]
With high probability, seems like its CUDA memory error. Can you try with lower width / height?

**Comment by Lukxie** [comment]
1 cycle at 1088x1088 (current)

Time taken: 11m 42.43sTorch active/reserved: 46598/72584 MiB, Sys VRAM: 74424/81070 MiB (91.8%)

1 cycle at 768x768

Time taken: 2m 28.70sTorch active/reserved: 18621/23822 MiB, Sys VRAM: 25662/81070 MiB (31.65%)

Both on same settings and same HN settings. Same error

Traceback (most recent call last):
  File "/notebooks/stable-diffusion-webui/extensions/Hypernetwork-MonkeyPatch-Extension-main/patches/external_pr/hypernetwork.py", line 213, in train_hypernetwork
    scaler.step(optimizer)
  File "/usr/local/lib/python3.9/dist-packages/torch/cuda/amp/grad_scaler.py", line 338, in step
    retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/cuda/amp/grad_scaler.py", line 285, in _maybe_opt_step
    retval = optimizer.step(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/optim/lr_scheduler.py", line 65, in wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/optim/optimizer.py", line 109, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/optim/adamw.py", line 161, in step
    adamw(params_with_grad,
  File "/usr/local/lib/python3.9/dist-packages/torch/optim/adamw.py", line 218, in adamw
    func(params,
  File "/usr/local/lib/python3.9/dist-packages/torch/optim/adamw.py", line 259, in _single_tensor_adamw
    assert not step_t.is_cuda, "If capturable=False, state_steps should not be CUDA tensors."
AssertionError: If capturable=False, state_steps should not be CUDA tensors.

**Comment by aria1th** [comment]
I could not reproduce the issue, maybe its very specific error by environment. Please reopen the issue if it does not get solved by patch
